os: linux
dist: xenial
sudo: required
compiler: gcc
language: cpp

addons:
  apt:
    packages:
    - libqt4-dev
    - libfftw3-dev

matrix:
  include:
    - env: NAME="gcc5 + Qt4 + release"
      script:
      - mkdir build-release
      - cd build-release
      - /usr/lib/x86_64-linux-gnu/qt4/bin/qmake ../src/SmartDeblur.pro CONFIG+=release
      - make -j2
    - env: NAME="gcc5 + Qt4 + debug"
      script:
      - mkdir build-release
      - cd build-release
      - /usr/lib/x86_64-linux-gnu/qt4/bin/qmake ../src/SmartDeblur.pro CONFIG+=debug
      - make -j2

